In [18]:
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

In [19]:
import tensorflow.keras as keras
import numpy as np
import pandas as pd

In [21]:
from sklearn.datasets import load_iris, fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
iris = load_iris()

In [5]:
iris_data = iris.data
iris_label = iris.target
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
x_train_full, x_test, y_train_full, y_test = train_test_split(iris_data, iris_label, test_size=0.1)

In [7]:
x_train, x_valid, y_train, y_valid = train_test_split(x_train_full, y_train_full)
x_train.shape, x_test.shape, x_valid.shape

((101, 4), (15, 4), (34, 4))

In [8]:
x_train_std = StandardScaler().fit_transform(x_train)
x_test_std = StandardScaler().fit_transform(x_test)
x_valid_std = StandardScaler().fit_transform(x_valid)

In [9]:
model = keras.models.Sequential([
    keras.layers.Dense(24, input_shape=(4, ), activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(3, activation='softmax'),
])

In [10]:
model.compile(loss = keras.losses.sparse_categorical_crossentropy,
             optimizer = keras.optimizers.Adam(lr=0.1),
             metrics = [keras.metrics.sparse_categorical_accuracy])

In [11]:
history = model.fit(x_train, y_train, epochs = 30, validation_data=(x_valid, y_valid))

Train on 101 samples, validate on 34 samples
Epoch 1/30
101/101 [==============================] - 0s 3ms/sample - loss: 2.1431 - sparse_categorical_accuracy: 0.3564 - val_loss: 1.1459 - val_sparse_categorical_accuracy: 0.3235
Epoch 2/30
101/101 [==============================] - 0s 109us/sample - loss: 1.1111 - sparse_categorical_accuracy: 0.3465 - val_loss: 1.0633 - val_sparse_categorical_accuracy: 0.5588
Epoch 3/30
101/101 [==============================] - 0s 118us/sample - loss: 1.0387 - sparse_categorical_accuracy: 0.5050 - val_loss: 1.0980 - val_sparse_categorical_accuracy: 0.2353
Epoch 4/30
101/101 [==============================] - 0s 104us/sample - loss: 0.9792 - sparse_categorical_accuracy: 0.3960 - val_loss: 0.9311 - val_sparse_categorical_accuracy: 0.5588
Epoch 5/30
101/101 [==============================] - 0s 109us/sample - loss: 0.6771 - sparse_categorical_accuracy: 0.6931 - val_loss: 0.7343 - val_sparse_categorical_accuracy: 0.5588
Epoch 6/30
101/101 [=================

In [12]:
model.evaluate(x_test, y_test, verbose=2)[1]

15/15 - 0s - loss: 0.0770 - sparse_categorical_accuracy: 1.0000


1.0

In [13]:
pred = model.predict(x_test)

In [14]:
np.mean(history.history['sparse_categorical_accuracy'])

0.8415842

In [15]:
y_test

array([0, 0, 2, 1, 2, 2, 2, 0, 2, 2, 1, 0, 1, 2, 1])

In [16]:
pred.round(2)

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.01, 0.95, 0.03],
       [0.  , 0.01, 0.99],
       [0.  , 0.12, 0.88],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.06, 0.94],
       [0.  , 0.28, 0.72],
       [0.02, 0.96, 0.03],
       [1.  , 0.  , 0.  ],
       [0.02, 0.96, 0.01],
       [0.  , 0.01, 0.99],
       [0.  , 0.62, 0.38]], dtype=float32)

In [22]:
housing = fetch_california_housing()

In [55]:
x_train_full, x_test, y_train_full, y_test = train_test_split(housing.data, housing.target)

In [56]:
x_train, x_valid, y_train, y_valid = train_test_split(x_train_full, y_train_full)

In [57]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_valid = scaler.transform(x_valid)
x_test = scaler.transform(x_test)

In [59]:
x_train.shape, x_valid.shape
x_train.shape[1:]

(8,)

In [71]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=x_train.shape[1:]),
    keras.layers.Dense(300, activation='elu', kernel_initializer='he_normal')
    ,
    keras.layers.Dense(100, activation='elu', kernel_initializer='he_normal'),
    keras.layers.Dense(1),
])

In [72]:
model.compile(loss = keras.losses.mean_squared_error,
             optimizer = keras.optimizers.Adam(lr=0.001),
             metrics = [keras.metrics.mean_squared_error])

In [75]:
history = model.fit(x_train, y_train, epochs=100, validation_data=(x_valid, y_valid))

Train on 11610 samples, validate on 3870 samples
Epoch 1/100
11610/11610 [==============================] - 1s 59us/sample - loss: 1.0282 - mean_squared_error: 1.0282 - val_loss: 0.9402 - val_mean_squared_error: 0.9402
Epoch 2/100
11610/11610 [==============================] - 0s 35us/sample - loss: 6.6405 - mean_squared_error: 6.6405 - val_loss: 1.0155 - val_mean_squared_error: 1.0155
Epoch 3/100
11610/11610 [==============================] - 0s 34us/sample - loss: 2.9825 - mean_squared_error: 2.9825 - val_loss: 1.5097 - val_mean_squared_error: 1.5097
Epoch 4/100
11610/11610 [==============================] - 0s 34us/sample - loss: 6.9337 - mean_squared_error: 6.9337 - val_loss: 2.4444 - val_mean_squared_error: 2.4444
Epoch 5/100
11610/11610 [==============================] - 0s 34us/sample - loss: 8.2034 - mean_squared_error: 8.2034 - val_loss: 3.3330 - val_mean_squared_error: 3.3330
Epoch 6/100
11610/11610 [==============================] - 0s 34us/sample - loss: 23.3216 - mean_squa

Epoch 49/100
11610/11610 [==============================] - 0s 33us/sample - loss: 0.4530 - mean_squared_error: 0.4530 - val_loss: 0.3076 - val_mean_squared_error: 0.3076
Epoch 50/100
11610/11610 [==============================] - 0s 33us/sample - loss: 0.3578 - mean_squared_error: 0.3578 - val_loss: 0.3128 - val_mean_squared_error: 0.3128
Epoch 51/100
11610/11610 [==============================] - 0s 37us/sample - loss: 0.3018 - mean_squared_error: 0.3018 - val_loss: 0.3095 - val_mean_squared_error: 0.3095
Epoch 52/100
11610/11610 [==============================] - 0s 37us/sample - loss: 0.2824 - mean_squared_error: 0.2824 - val_loss: 0.3047 - val_mean_squared_error: 0.3047
Epoch 53/100
11610/11610 [==============================] - 0s 34us/sample - loss: 0.2803 - mean_squared_error: 0.2803 - val_loss: 0.3025 - val_mean_squared_error: 0.3025
Epoch 54/100
11610/11610 [==============================] - 0s 35us/sample - loss: 0.2776 - mean_squared_error: 0.2776 - val_loss: 0.3085 - val_m

Epoch 97/100
11610/11610 [==============================] - 0s 33us/sample - loss: 0.2385 - mean_squared_error: 0.2385 - val_loss: 0.2914 - val_mean_squared_error: 0.2914
Epoch 98/100
11610/11610 [==============================] - 0s 32us/sample - loss: 0.2395 - mean_squared_error: 0.2395 - val_loss: 0.2944 - val_mean_squared_error: 0.2944
Epoch 99/100
11610/11610 [==============================] - 0s 33us/sample - loss: 0.2368 - mean_squared_error: 0.2368 - val_loss: 0.3151 - val_mean_squared_error: 0.3151
Epoch 100/100
11610/11610 [==============================] - 0s 35us/sample - loss: 0.2349 - mean_squared_error: 0.2349 - val_loss: 0.2984 - val_mean_squared_error: 0.2984


In [78]:
model.evaluate(x_test, y_test, verbose=2)

5160/5160 - 0s - loss: 0.3063 - mean_squared_error: 0.3063


[0.3063493803374527, 0.30634937]

In [79]:
x_new = x_test[:3]

In [81]:
y_pred = model.predict(x_new)

In [84]:
x_new

array([[ 0.59734788, -1.48477161,  0.10979906, -0.14955127,  0.37476284,
        -0.03764575, -0.63813809,  0.45515502],
       [ 2.79715446, -0.29129361,  0.16122114, -0.31663213, -1.00571187,
        -0.00476541,  0.98293457, -1.09361542],
       [-0.54976781, -0.76868481, -0.44164838, -0.25005976,  0.30853445,
        -0.08106309,  1.26323532, -1.55824655]])

In [83]:
y_pred.round(2)

array([[2.7 ],
       [3.9 ],
       [1.66]], dtype=float32)