In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

Using plaidml.keras.backend backend.


In [3]:
df = pd.read_csv('../dataset/iris.csv', names = ["sepal_length",
                 "sepal_width", "petal_length", "petal_width", "species"])

In [4]:
dataset = df.values

In [5]:
x_data = dataset[:, :-1].astype(np.float32)
y = dataset[:, -1]

In [6]:
labels = LabelEncoder()
labels.fit(y)
y_data = labels.transform(y)

In [7]:
y_data = np_utils.to_categorical(y_data)

In [8]:
# y_data2 = tf.one_hot(y_data, 3)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, stratify=y_data, test_size=0.2, random_state=2020)

In [58]:
x_train.shape, y_train.shape

((120, 4), (120,))

In [10]:
model = Sequential([
    Dense(100, input_shape=(4, ), activation='relu'),
    Dense(50, activation='relu'),
    Dense(25, activation='relu'),
    Dense(3, activation='softmax')
])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               500       
_________________________________________________________________
dense_1 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_2 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 78        
Total params: 6,903
Trainable params: 6,903
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss=keras.losses.categorical_crossentropy,
             optimizer = 'nadam',
             metrics = ['accuracy'])

In [13]:
history = model.fit(x_train, y_train, epochs = 100 , batch_size=10, validation_split=0.2)

Train on 96 samples, validate on 24 samples
Epoch 1/100
96/96 [==============================] - 1s 7ms/sample - loss: 1.2221 - accuracy: 0.3333 - val_loss: 0.9811 - val_accuracy: 0.7083
Epoch 2/100
96/96 [==============================] - 0s 230us/sample - loss: 0.9523 - accuracy: 0.6146 - val_loss: 0.8625 - val_accuracy: 0.8750
Epoch 3/100
96/96 [==============================] - 0s 170us/sample - loss: 0.8365 - accuracy: 0.6875 - val_loss: 0.7617 - val_accuracy: 0.6667
Epoch 4/100
96/96 [==============================] - 0s 187us/sample - loss: 0.7330 - accuracy: 0.7708 - val_loss: 0.6627 - val_accuracy: 0.6667
Epoch 5/100
96/96 [==============================] - 0s 175us/sample - loss: 0.6453 - accuracy: 0.7083 - val_loss: 0.5747 - val_accuracy: 0.8333
Epoch 6/100
96/96 [==============================] - 0s 169us/sample - loss: 0.5713 - accuracy: 0.7604 - val_loss: 0.5076 - val_accuracy: 0.8333
Epoch 7/100
96/96 [==============================] - 0s 177us/sample - loss: 0.5204 - ac

In [15]:
model.evaluate(x_test, y_test)[1]

30/30 [==============================] - 0s 57us/sample - loss: 0.0854 - accuracy: 0.9333


0.93333334

In [ ]:
# one_hot

In [45]:
keras.backend.clear_session()

In [46]:
x_data = np.array(dataset[:, :-1]).astype(np.float32)
y = dataset[:, -1]

In [47]:
labels = LabelEncoder().fit(y)
y_data = np.array(labels.transform(y))

In [48]:
y_one_hot = tf.one_hot(y_data, 3)
y_one_hot[0], y_one_hot[50], y_one_hot[100]

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 0.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 1.], dtype=float32)>)

In [51]:
model = Sequential([
    Dense(100, input_shape=(4, ), activation='relu'),
    Dense(50, activation='relu'),
    Dense(25, activation='relu'),
    Dense(3, activation='softmax')
])

In [53]:
model.compile(loss=keras.losses.categorical_crossentropy,
             optimizer = 'nadam',
             metrics = ['accuracy'])

In [56]:
model.fit(x_data, y_one_hot, epochs=50)

Train on 150 samples
Epoch 1/50
150/150 [==============================] - 1s 3ms/sample - loss: 1.0444 - accuracy: 0.6333
Epoch 2/50
150/150 [==============================] - 0s 51us/sample - loss: 0.9409 - accuracy: 0.9000
Epoch 3/50
150/150 [==============================] - 0s 43us/sample - loss: 0.8617 - accuracy: 0.6667
Epoch 4/50
150/150 [==============================] - 0s 46us/sample - loss: 0.7918 - accuracy: 0.7000
Epoch 5/50
150/150 [==============================] - 0s 47us/sample - loss: 0.7251 - accuracy: 0.6667
Epoch 6/50
150/150 [==============================] - 0s 47us/sample - loss: 0.6557 - accuracy: 0.7067
Epoch 7/50
150/150 [==============================] - 0s 33us/sample - loss: 0.5766 - accuracy: 0.7267
Epoch 8/50
150/150 [==============================] - 0s 53us/sample - loss: 0.5188 - accuracy: 0.8933
Epoch 9/50
150/150 [==============================] - 0s 47us/sample - loss: 0.4664 - accuracy: 0.8467
Epoch 10/50
150/150 [==============================] 

In [57]:
model.evaluate(x_data, y_one_hot, verbose=2)

150/150 - 0s - loss: 0.0728 - accuracy: 0.9800


[0.07279197485496601, 0.98]