In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

Using plaidml.keras.backend backend.


In [3]:
df = pd.read_csv('../dataset/sonar.csv', header=None)
df.head(3)

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  

[3 rows x 61 columns]

In [4]:
x_data = df.iloc[:, :-1].astype(np.float32)
y = df.iloc[:, -1]

In [5]:
x_data = np.array(x_data)

In [6]:
oh = LabelEncoder().fit(y)
y_data = np.array(oh.transform(y), dtype=np.float32)

In [7]:
# y_data = np_utils.to_categorical(y_data)

In [8]:
y_data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.], dtype=float32)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, stratify=y_data, test_size=0.3, random_state=2020)

In [10]:
model = Sequential([
    Dense(30, input_dim=60, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [11]:
model.compile(loss = 'binary_crossentropy',
             optimizer = 'nadam',
             metrics = ['accuracy'])

In [12]:
history = model.fit(x_train, y_train, epochs=130, batch_size=5, validation_split=0.2)

Train on 116 samples, validate on 29 samples
Epoch 1/130
116/116 [==============================] - 1s 5ms/sample - loss: 0.7072 - accuracy: 0.5517 - val_loss: 0.6938 - val_accuracy: 0.4828
Epoch 2/130
116/116 [==============================] - 0s 294us/sample - loss: 0.6472 - accuracy: 0.6466 - val_loss: 0.6823 - val_accuracy: 0.5517
Epoch 3/130
116/116 [==============================] - 0s 257us/sample - loss: 0.6253 - accuracy: 0.6983 - val_loss: 0.6714 - val_accuracy: 0.5862
Epoch 4/130
116/116 [==============================] - 0s 264us/sample - loss: 0.6077 - accuracy: 0.7328 - val_loss: 0.6603 - val_accuracy: 0.6207
Epoch 5/130
116/116 [==============================] - 0s 247us/sample - loss: 0.5953 - accuracy: 0.7155 - val_loss: 0.6684 - val_accuracy: 0.5862
Epoch 6/130
116/116 [==============================] - 0s 258us/sample - loss: 0.5818 - accuracy: 0.7069 - val_loss: 0.6437 - val_accuracy: 0.6897
Epoch 7/130
116/116 [==============================] - 0s 249us/sample - lo

In [13]:
model.evaluate(x_test, y_test, verbose=2)[1]

63/63 - 0s - loss: 0.5076 - accuracy: 0.8095


0.8095238

In [14]:
model.save('../model/my_first_model.h5')

In [18]:
del model

In [20]:
model = keras.models.load_model('../model/my_first_model.h5')

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 30)                1830      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 31        
Total params: 1,861
Trainable params: 1,861
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.evaluate(x_test, y_test)

63/63 [==============================] - 0s 939us/sample - loss: 0.5076 - accuracy: 0.8095


[0.5075944699938335, 0.8095238]

In [23]:
dir(model)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_inbound_node',
 '_add_trackable',
 '_add_unique_metric_name',
 '_add_variable_with_custom_getter',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_attribute_sentinel',
 '_autocast',
 '_base_init',
 '_build_input_shape',
 '_build_model_with_inputs',
 '_cache_output_metric_attributes',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_args',
 '_call_full_argspec',
 '_callable_losses',
 '_check_call_args',
 '_check_trainable_weights_consistency',
 '_checkpoint_dependencies',
 '_clear_losse

In [24]:
# 가중치
model.weights

[<tf.Variable 'dense_3/kernel:0' shape=(60, 30) dtype=float32, numpy=
 array([[-0.06631696,  0.5657591 , -0.6077202 , ...,  0.5923287 ,
          0.6015908 , -0.671359  ],
        [-0.20465685,  0.48135883, -0.38774386, ...,  0.08841794,
          0.33712086,  0.02385171],
        [-0.20224415, -0.048456  , -0.50845987, ...,  0.0858119 ,
          0.05015892,  0.3473314 ],
        ...,
        [ 0.08654091,  0.3194313 , -1.0640658 , ...,  0.23783335,
          0.03231017,  0.1943705 ],
        [-0.15358347,  0.04933497, -0.37113717, ...,  0.0532144 ,
          0.16883366,  0.42483276],
        [ 0.06946117,  0.06702598, -0.4847488 , ..., -0.01013245,
          0.21498723,  0.33820665]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(30,) dtype=float32, numpy=
 array([ 0.        , -0.10362824,  0.15571539,  0.15184803, -0.10162906,
        -0.0889606 , -0.08239542, -0.15832807,  0.12708405, -0.09420016,
        -0.05605504,  0.08918205,  0.11519143,  0.        ,  0.15958892,
   

In [30]:
len(model.weights)

4

In [35]:
for i in range(len(model.weights)):
    print(i, model.weights[i].shape)

0 (60, 30)
1 (30,)
2 (30, 1)
3 (1,)
