In [16]:
import plaidml.keras
plaidml.keras.install_backend()

In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
seed = 2020
np.random.seed(seed)
tf.set_random_seed(seed)

In [5]:
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0]).reshape(-1, 1)
x_data.shape, y_data.shape

((4, 2), (4, 1))

In [6]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [9]:
w1 = tf.Variable(tf.random_uniform([2,2], dtype=tf.float32))
b1 = tf.Variable(tf.random_uniform([2], dtype=tf.float32))
l1 = tf.sigmoid(tf.matmul(X, w1) + b1)

In [10]:
w2 = tf.Variable(tf.random_uniform([2,1], dtype=tf.float32))
b2 = tf.Variable(tf.random_uniform([1], dtype=tf.float32))
hypothesis = tf.sigmoid(tf.matmul(l1, w2) + b2)

In [11]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [12]:
lr = 0.1
train = tf.train.AdamOptimizer(lr).minimize(cost)

In [14]:
predicted = tf.cast(hypothesis > 0.5 , dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,  hypothesis), dtype=tf.float32))

In [17]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val=sess.run([train, cost], feed_dict={X : x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    
    h, p, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    W1_, b1_, W2_, b2_ = sess.run([w1, b1, w2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 0.72075504
1000 0.00091795647
2000 0.00027107488
3000 0.00011990212
4000 6.1648054e-05
5000 3.4094453e-05
6000 1.9580322e-05
7000 1.1518666e-05
8000 6.839657e-06
9000 4.1276303e-06
10000 2.4437936e-06

Hypothesis:
[[2.3488794e-06]
 [9.9999785e-01]
 [9.9999785e-01]
 [3.1474592e-06]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
0.0

W1:
[[-12.969869 -10.751627]
 [-12.951524 -10.761459]] 
b1:
[ 6.088148 15.997299] 
W2:
[[-26.213873]
 [ 25.965895]]
b1:
[-12.772948]
